import type { Contact, Faq, Inquiry, Offer, Package, Settings, Testimonial } from "./domain";
export const packages: Package[] = [
 {id:"p1",slug:"signature-umrah-14-nights",title:"Signature Umrah — 14 Nights",duration:15,nightsMakkah:8,nightsMadinah:6,price:349000,previousPrice:369000,departure:"12 December 2026",airline:"Direct / one-stop options",hotelMakkah:"Premium hotel near Haram",hotelMadinah:"Premium hotel near Masjid an-Nabawi",distanceMakkah:"Approx. 450 m",distanceMadinah:"Approx. 350 m",image:"makkah",featured:true,status:"published",tags:["Most requested","Family"],summary:"A carefully paced pilgrimage with guided support, comfortable stays, and private transfers.",inclusions:["Return economy airfare","Visa processing support","Hotel accommodation","Ziyarat tours","Airport and intercity transfers","Group guidance"],exclusions:["Personal expenses","Meals not listed","Travel insurance"],documents:["Passport valid for 6 months","Recent passport photographs","Vaccination records where required"],itinerary:[{day:"Days 1–2",title:"Arrival in Makkah",detail:"Airport welcome, private transfer, check-in and guided orientation."},{day:"Days 3–8",title:"Makkah stay",detail:"Worship time, guided ziyarat and dedicated group support."},{day:"Days 9–14",title:"Madinah stay",detail:"Intercity transfer, Masjid an-Nabawi access and historical ziyarat."},{day:"Day 15",title:"Return",detail:"Hotel checkout and assisted airport transfer."}]},
 {id:"p2",slug:"comfort-umrah-10-nights",title:"Comfort Umrah — 10 Nights",duration:11,nightsMakkah:6,nightsMadinah:4,price:279000,departure:"18 January 2027",airline:"Economy airfare",hotelMakkah:"Comfort hotel in central Makkah",hotelMadinah:"Comfort hotel in central Madinah",distanceMakkah:"Approx. 700 m",distanceMadinah:"Approx. 500 m",image:"hotel",featured:true,status:"published",tags:["Best value"],summary:"A balanced shorter journey with dependable hotels and coordinated ground support.",inclusions:["Return economy airfare","Visa support","Hotel accommodation","Shared transfers","Guided ziyarat"],exclusions:["Personal expenses","Travel insurance"],documents:["Valid passport","Passport photographs"],itinerary:[{day:"Days 1–6",title:"Makkah",detail:"Arrival, Umrah support and Makkah ziyarat."},{day:"Days 7–10",title:"Madinah",detail:"Madinah transfer, worship and ziyarat."},{day:"Day 11",title:"Departure",detail:"Airport transfer and return flight."}]},
 {id:"p3",slug:"ramadan-last-ashra",title:"Ramadan Last Ashra",duration:12,nightsMakkah:7,nightsMadinah:4,price:525000,departure:"Ramadan 2027",airline:"Flexible economy routing",hotelMakkah:"Selected Ramadan hotel",hotelMadinah:"Selected Madinah hotel",distanceMakkah:"Approx. 500 m",distanceMadinah:"Approx. 400 m",image:"madinah",featured:true,status:"published",tags:["Limited","Ramadan"],summary:"A spiritually focused Ramadan itinerary with carefully managed transfers and support.",inclusions:["Airfare","Visa support","Selected hotels","Suhoor and Iftar where listed","Transfers","Ziyarat"],exclusions:["Personal expenses","Optional room upgrades"],documents:["Valid passport","Passport photographs","Required health documentation"],itinerary:[{day:"Days 1–4",title:"Madinah",detail:"Arrival and focused time at Masjid an-Nabawi."},{day:"Days 5–11",title:"Makkah",detail:"Transfer to Makkah and Last Ashra worship schedule."},{day:"Day 12",title:"Return",detail:"Assisted airport transfer."}]},
 {id:"p4",slug:"essential-umrah-7-nights",title:"Essential Umrah — 7 Nights",duration:8,nightsMakkah:4,nightsMadinah:3,price:229000,departure:"08 February 2027",airline:"Economy airfare",hotelMakkah:"Selected 3-star hotel",hotelMadinah:"Selected 3-star hotel",distanceMakkah:"Shuttle access",distanceMadinah:"Approx. 650 m",image:"transport",featured:false,status:"published",tags:["Short stay"],summary:"A focused itinerary for travelers seeking a shorter, well-supported pilgrimage.",inclusions:["Airfare","Visa support","Hotels","Transfers"],exclusions:["Meals","Personal expenses"],documents:["Valid passport","Passport photographs"],itinerary:[{day:"Days 1–4",title:"Makkah",detail:"Umrah and worship schedule."},{day:"Days 5–7",title:"Madinah",detail:"Madinah stay and ziyarat."},{day:"Day 8",title:"Return",detail:"Airport transfer."}]}
];
export const offers: Offer[]=[{id:"o1",title:"Family room upgrade",description:"Preferential upgrade pricing on selected winter departures.",badge:"Seasonal demo offer",validUntil:"2026-12-15",active:true},{id:"o2",title:"Early confirmation benefit",description:"Reserve selected 2027 departures with a reduced initial deposit.",badge:"Configurable offer",validUntil:"2026-11-30",active:true}];
export const faqs: Faq[]=[{id:"f1",question:"When should I book my Umrah package?",answer:"Early planning gives you a wider choice of flights, hotels, and room types. Ramadan and school-holiday dates usually require more lead time.",category:"Booking",active:true,order:1},{id:"f2",question:"Is visa processing included?",answer:"Visa processing support is included where shown. Final approval remains with the relevant authorities.",category:"Documents",active:true,order:2},{id:"f3",question:"Can a package be customized?",answer:"Yes. Tell our team your dates, travelers, room preference, and departure city for a tailored proposal.",category:"Packages",active:true,order:3},{id:"f4",question:"What documents are generally required?",answer:"A valid passport, recent photographs, and any current health documentation are commonly required. We confirm the latest checklist before submission.",category:"Documents",active:true,order:4}];
export const testimonials: Testimonial[]=[{id:"t1",name:"Demo traveler",city:"Karachi",quote:"The itinerary felt calm and the group guidance was clear at every stage.",rating:5,active:true,order:1,demo:true},{id:"t2",name:"Demo family",city:"Lahore",quote:"Hotel and transfer details were communicated carefully before departure.",rating:5,active:true,order:2,demo:true}];
export const inquiries: Inquiry[]=[{id:"i1",name:"Demo enquiry",phone:"0300 0000000",packageTitle:"Signature Umrah — 14 Nights",travelers:4,status:"new",createdAt:"2026-09-21"},{id:"i2",name:"Sample family",phone:"0311 0000000",packageTitle:"Comfort Umrah — 10 Nights",travelers:3,status:"contacted",createdAt:"2026-09-20"}];
export const contacts: Contact[]=[{id:"c1",name:"Sample visitor",email:"demo@example.com",phone:"0322 0000000",subject:"Custom package",message:"We need a configurable family proposal.",status:"unread",createdAt:"2026-09-21"}];
export const settings: Settings={agencyName:"Safar e Harmain",phone:"+92 300 0000000",whatsapp:"923000000000",email:"hello@example.com",address:"Pakistan office address — configure before launch",tagline:"Thoughtfully planned journeys to the Two Holy Mosques"};
